pipeline {
    agent any

	environment {
        TEST_RESULTS_DIR = "test-results"
        PERFORMANCE_RESULTS_DIR = "performance-results"
    }
	
    stages {
        stage('Checkout') {
            steps {
                // 소스코드를 체크아웃
                checkout scm
            }
        }

        stage('Build') {
            steps {
                // Java 파일들을 컴파일하여 생성된 클래스 파일을 classes 디렉토리에 저장
                sh 'mkdir -p classes'
                sh 'javac -encoding UTF-8 -cp "SE_Mission/libs/*" -d classes SE_Mission/src/*.java'
				
            }
        }

        stage('Test') {
            steps {
                // JUnit 5 테스트 실행을 위한 classpath 설정
                script {
                    // def classpath = "classes:lib/*:path/to/eclipse/plugins/junit-platform-console-standalone-1.7.1.jar"
                    def classpath = "SE_Mission/libs/junit-platform-console-standalone-1.7.1.jar"
                    // JUnit 5 테스트 실행
                    sh "java -cp ${classpath} org.junit.platform.console.ConsoleLauncher --scan-classpath > test_results.txt"
                }
            }
        }
        
        stage('Performance Test') {
            steps {
                // 성능 테스트 실행
                script {
                	def classpath = "SE_Mission/libs/junit-platform-console-standalone-1.7.1.jar"
                    // 성능 테스트 결과 디렉토리 생성
                    sh "mkdir -p ${PERFORMANCE_RESULTS_DIR}"
                    // 성능 테스트 실행 및 결과 저장
                    sh "java -cp ${classpath} org.junit.platform.console.ConsoleLauncher --select-class BookPerformanceTest --reports-dir=${PERFORMANCE_RESULTS_DIR} > ${PERFORMANCE_RESULTS_DIR}/performance_test_results.txt"
                }
            }
        }
    }

    post {
        always {
            // 테스트 결과 파일을 저장하기 위해 아카이브
            archiveArtifacts "${TEST_RESULTS_DIR}/**/*"
            archiveArtifacts "${PERFORMANCE_RESULTS_DIR}/**/*"
        }
        failure {
            echo 'Build or test failed'
        }
        success {
            echo 'Build and test succeeded'
        }
    }
}
